### ISSUE TITLE
Clip sound before each metronome beat

### ISSUE THREAD

**Issue by senyuuri** [pyxyyy/gesture-drumkit#26]
Can also be heard at the end of each `kick.wav` sound. 

A few hypotheses:
- sample may have been cropped at the beginning/end due to processing delay
- incompatible sampling rate/bit depth (unlikely)
- ?

**Comment by alexfjw** [comment]
Hmm.. should we try to artificially extend the sample / make it fade or smth. 
Crossfade between each beat? (if that makes sense)
