### ISSUE TITLE
Hookup DrumKit UI to DrumMachine code

### ISSUE THREAD

**Issue by alexfjw** [pyxyyy/gesture-drumkit#31]
Blocked on pending updates to DrumMachine API.
1) setBeat(row) should return the column the beat is added
2) start() should take in a start beat index

**Comment by senyuuri** [comment]
Known bugs:

- [x] Metronome sound stop playing after `stop` ->  `change tempo` -> `play`
- [x] No sound after `move seek bar` -> `play`

**Comment by senyuuri** [comment]
LockFreeQueue was acting weird sometimes and returned incorrect elements.

Fixed in #33 . Have replaced it with std::queue. So far std::queue has not shown any significant performance impact so I think we just need to keep an eye on it.
