### ISSUE TITLE
Estimate duration of gesture

### ISSUE THREAD

**Issue by alexfjw** [pyxyyy/gesture-drumkit#32]
Since the windows of data fed into the model has fixed length, we can only predict if user has made a gesture, but not the duration of the gesture*. 

The duration can be estimated by from accelerometer data. Acceleration should be at a minimum in the direction of the gesture.

*strictly speaking, we could have the model try, but small window size makes very difficult. it also requires a lot more annotated data

**Comment by senyuuri** [comment]
> The duration can be estimated by from accelerometer data. Acceleration should be at a minimum in the direction of the gesture.

Maybe we can define an offset event to be some "inactivity" of the accelerometer for a threshold  `x` & a duration of `y` consecutive frames? Then any data falls between the onset-offset range will become the gesture's movement.

> *strictly speaking, we could have the model try, but small window size makes very difficult. it also requires a lot more annotated data

Agree. It needs all data to be annotated with both onset & offset events which effectively doubles our workload... Let's keep it simple first.

**Comment by alexfjw** [comment]
Still undecided if trying but this is probably smth that might work:
-> when a gesture is detected, look for the 0 acceleration point in the window used
-> figure out how the acceleration values usually look like when a gesture is detected
-> work backwards 30 or so frames (depends on findings from prev step) & get the largest change in rate of change of acceleration
-> record maximum rate of change & minimum rate of change without making exaggerated gestures, then segment that into a few volume levels.

**Comment by alexfjw** [comment]
Closing, this is a high cost & low yield experiment.
